### ISSUE TITLE
Web Front End config example missing

### ISSUE THREAD

**Issue by libbyh** [bitslabsyr/stack#10]
The wiki refers to a ```stack.conf``` file to use with Apache, but the example it refers to is missing from the repo. The wiki referred to a Facebook branch that I can't see that maybe had it?

https://github.com/bitslabsyr/stack/wiki/Web-Front-End

**Comment by stanupab** [comment]
The wiki was fixed with an instruction to create the file (step 5).

**Comment by libbyh** [comment]
Thanks! I was able to get it working.
