### ISSUE TITLE
Repo weblink to university of syracuse is dead

### ISSUE THREAD

**Issue by sgoggins** [bitslabsyr/stack#41]
I personally blame whoever gave Steve Sawyer root privileges on your server.

Sean

**Comment by sgoggins** [comment]
http://bits.ischool.syr.edu/

**Comment by sgoggins** [comment]
@jintrone : Why is this urgent issue not being addressed?

Don't make me stop this car!

**Comment by jintrone** [comment]
Lol.  I’ll get right on that, Dad.

On Apr 1, 2021, at 4:01 PM, Sean P. Goggins ***@***.******@***.***>> wrote:



@jintrone<https://urldefense.com/v3/__https://github.com/jintrone__;!!HXCxUKc!gnu5RWB9_I_-bRlMxTT-4OynsAY4o0Z7oEv1XI-_QayA6HxM_3-oDQEsucBwBfc$> : Why is this urgent issue not being addressed?

Don't make me stop this car!

**Comment by sgoggins** [comment]
Thanks,son! Hard to believe I'm 30 years younger than you and still your dad 🤣

**Comment by jintrone** [comment]
Phew!  Load off my mind.  Grandpa.
